package app.pages;

import app.config.ApiClient;
import app.session.UserSession;
import app.config.ApiConfig;
import app.datos.Datos_per;
import com.google.gson.Gson;
/*import java.io.OutputStream;
import java.net.HttpURLConnection;
import java.net.URL;*/

public class Pg_info_per extends javax.swing.JPanel {

    public Pg_info_per() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        Title = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Subtext_nom = new javax.swing.JLabel();
        txf_nombre = new javax.swing.JTextField();
        Label_nom = new javax.swing.JLabel();
        Subtext_Tdoc = new javax.swing.JLabel();
        tipo_doc = new javax.swing.JComboBox<>();
        Label_Tdoc = new javax.swing.JLabel();
        Subtext_doc = new javax.swing.JLabel();
        txf_documento = new javax.swing.JTextField();
        Label_doc = new javax.swing.JLabel();
        Subtext_nac = new javax.swing.JLabel();
        txf_fecha_na = new javax.swing.JTextField();
        Label_nac = new javax.swing.JLabel();
        Subtext_edad = new javax.swing.JLabel();
        txf_edad = new javax.swing.JTextField();
        Label_edad = new javax.swing.JLabel();
        Subtext_nacionalidad = new javax.swing.JLabel();
        txf_nacional = new javax.swing.JTextField();
        Label_nacional = new javax.swing.JLabel();
        bt_guardar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Subtitle = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        Decoration1 = new javax.swing.JLabel();
        Decoration2 = new javax.swing.JLabel();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(991, 720));
        setPreferredSize(new java.awt.Dimension(991, 720));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Title.setFont(new java.awt.Font("Overpass", 1, 48)); // NOI18N
        Title.setForeground(new java.awt.Color(68, 75, 89));
        Title.setText("Información General");
        add(Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        jPanel1.setBackground(new java.awt.Color(250, 250, 250));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Subtext_nom.setFont(new java.awt.Font("Nunito ExtraLight", 1, 14)); // NOI18N
        Subtext_nom.setForeground(new java.awt.Color(68, 75, 89));
        Subtext_nom.setText("Nombre completo");
        jPanel1.add(Subtext_nom, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 166, 20));

        txf_nombre.setBackground(new java.awt.Color(250, 250, 250));
        txf_nombre.setFont(new java.awt.Font("Overpass", 1, 14)); // NOI18N
        txf_nombre.setBorder(null);
        txf_nombre.setOpaque(false);
        txf_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txf_nombreActionPerformed(evt);
            }
        });
        jPanel1.add(txf_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 230, 40));

        Label_nom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Label.png"))); // NOI18N
        jPanel1.add(Label_nom, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, -1));

        Subtext_Tdoc.setFont(new java.awt.Font("Nunito ExtraLight", 0, 14)); // NOI18N
        Subtext_Tdoc.setForeground(new java.awt.Color(68, 75, 89));
        Subtext_Tdoc.setText("Tipo de documento");
        jPanel1.add(Subtext_Tdoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 198, -1));

        tipo_doc.setBackground(new java.awt.Color(250, 250, 250));
        tipo_doc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CC", "TI", "CE", "PP" }));
        tipo_doc.setBorder(null);
        tipo_doc.setOpaque(false);
        tipo_doc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipo_docActionPerformed(evt);
            }
        });
        jPanel1.add(tipo_doc, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 230, 20));

        Label_Tdoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Label.png"))); // NOI18N
        jPanel1.add(Label_Tdoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, -1, -1));

        Subtext_doc.setFont(new java.awt.Font("Nunito ExtraLight", 0, 14)); // NOI18N
        Subtext_doc.setForeground(new java.awt.Color(68, 75, 89));
        Subtext_doc.setText("Número de documento");
        jPanel1.add(Subtext_doc, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 198, -1));

        txf_documento.setBackground(new java.awt.Color(250, 250, 250));
        txf_documento.setFont(new java.awt.Font("Overpass", 1, 14)); // NOI18N
        txf_documento.setBorder(null);
        txf_documento.setOpaque(false);
        txf_documento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txf_documentoActionPerformed(evt);
            }
        });
        jPanel1.add(txf_documento, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 230, 40));

        Label_doc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Label.png"))); // NOI18N
        jPanel1.add(Label_doc, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, -1, -1));

        Subtext_nac.setFont(new java.awt.Font("Nunito ExtraLight", 0, 14)); // NOI18N
        Subtext_nac.setForeground(new java.awt.Color(68, 75, 89));
        Subtext_nac.setText("Fecha de nacimiento");
        jPanel1.add(Subtext_nac, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 139, -1));

        txf_fecha_na.setBackground(new java.awt.Color(250, 250, 250));
        txf_fecha_na.setFont(new java.awt.Font("Overpass", 1, 14)); // NOI18N
        txf_fecha_na.setBorder(null);
        txf_fecha_na.setOpaque(false);
        jPanel1.add(txf_fecha_na, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, 230, 40));

        Label_nac.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Label.png"))); // NOI18N
        jPanel1.add(Label_nac, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, -1, -1));

        Subtext_edad.setFont(new java.awt.Font("Nunito ExtraLight", 0, 14)); // NOI18N
        Subtext_edad.setForeground(new java.awt.Color(68, 75, 89));
        Subtext_edad.setText("Edad");
        jPanel1.add(Subtext_edad, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, 40, -1));

        txf_edad.setBackground(new java.awt.Color(250, 250, 250));
        txf_edad.setFont(new java.awt.Font("Overpass", 1, 14)); // NOI18N
        txf_edad.setBorder(null);
        txf_edad.setOpaque(false);
        txf_edad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txf_edadActionPerformed(evt);
            }
        });
        jPanel1.add(txf_edad, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, 230, 40));

        Label_edad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Label.png"))); // NOI18N
        jPanel1.add(Label_edad, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, -1, -1));

        Subtext_nacionalidad.setFont(new java.awt.Font("Nunito ExtraLight", 0, 14)); // NOI18N
        Subtext_nacionalidad.setForeground(new java.awt.Color(68, 75, 89));
        Subtext_nacionalidad.setText("Nacionalidad");
        jPanel1.add(Subtext_nacionalidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, 90, -1));

        txf_nacional.setBackground(new java.awt.Color(250, 250, 250));
        txf_nacional.setFont(new java.awt.Font("Overpass", 1, 14)); // NOI18N
        txf_nacional.setBorder(null);
        txf_nacional.setOpaque(false);
        jPanel1.add(txf_nacional, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 400, 230, 40));

        Label_nacional.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Label.png"))); // NOI18N
        Label_nacional.setOpaque(false);
        jPanel1.add(Label_nacional, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 400, -1, -1));

        bt_guardar.setFont(new java.awt.Font("Overpass", 1, 18)); // NOI18N
        bt_guardar.setForeground(new java.awt.Color(255, 255, 255));
        bt_guardar.setText("Guardar");
        bt_guardar.setBorder(null);
        bt_guardar.setContentAreaFilled(false);
        bt_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_guardarActionPerformed(evt);
            }
        });
        jPanel1.add(bt_guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 453, 130, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Sign In.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 450, -1, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 160, 360, 520));

        Subtitle.setFont(new java.awt.Font("Overpass", 0, 24)); // NOI18N
        Subtitle.setForeground(new java.awt.Color(68, 75, 89));
        Subtitle.setText("Identificación básica");
        add(Subtitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 130, -1, -1));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 900, -1));

        Decoration1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Decorations.png"))); // NOI18N
        add(Decoration1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 190, -1, -1));

        Decoration2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/decoration2.png"))); // NOI18N
        add(Decoration2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-70, 180, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void bt_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_guardarActionPerformed

        //1. Validar campos vacíos
        
        if (txf_nombre.getText().trim().isEmpty() ||
        txf_fecha_na.getText().trim().isEmpty() ||
        txf_documento.getText().trim().isEmpty() ||
        txf_edad.getText().trim().isEmpty() ||
        txf_nacional.getText().trim().isEmpty()) {
        
        javax.swing.JOptionPane.showMessageDialog(this,
            "Por favor complete todos los campos antes de continuar.",
            "Campos incompletos",
        javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
        }
        
        //2. Validar que documento y edad sean numéricos
        
        int edad = 0;
        try {
            edad = Integer.parseInt(txf_edad.getText().trim());
            if (edad <= 0 || edad > 120) {
                javax.swing.JOptionPane.showMessageDialog(this,
                    "Ingrese una edad válida (entre 1 y 120 años).",
                    "Edad inválida",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "La edad debe ser un número válido.",
                "Dato inválido",
                javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        try {
            Long.parseLong(txf_documento.getText().trim());
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "El número de documento debe contener solo dígitos.",
                "Documento inválido",
                javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        //3. Validar formato de fecha (AAAA-MM-DD)
        
        if (!txf_fecha_na.getText().matches("\\d{4}-\\d{2}-\\d{2}")) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "La fecha debe tener el formato AAAA-MM-DD (por ejemplo: 2000-05-23).",
                "Formato incorrecto",
                javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        //4. Crear objeto con los datos del formulario
        
        Datos_per persona = new Datos_per();
        persona.setNombreCompleto(txf_nombre.getText().trim());
        persona.setTipoDocumento(tipo_doc.getSelectedItem().toString());
        persona.setNumeroDocumento(txf_documento.getText().trim());
        persona.setFechaNacimiento(txf_fecha_na.getText().trim());
        persona.setEdad(edad);
        persona.setNacionalidad(txf_nacional.getText().trim());


        //5. Convertir a JSON
        Gson gson = new Gson();
        String jsonPersona = gson.toJson(persona);

        System.out.println("Persona en JSON:");
        System.out.println(jsonPersona);

        //6. Verificar sesión
        String token = UserSession.getInstance().getToken();
        if (token == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "No hay sesión activa.");
            return;
        }

        //7. Enviar datos con mónada Try (ApiClient)
        ApiClient.enviarDatos(ApiConfig.PERSONAS_URL + "info_personal", jsonPersona, token)
                .onSuccess(status -> {
                    System.out.println("Código de respuesta: " + status);
                    javax.swing.JOptionPane.showMessageDialog(this, "Datos enviados correctamente");
                })
                .onFailure(e -> {
                    e.printStackTrace();
                    javax.swing.JOptionPane.showMessageDialog(this, "Error al enviar: " + e.getMessage());
                });

        //8. Limpiar campos después de guardar
        txf_documento.setText("");
        txf_edad.setText("");
        txf_fecha_na.setText("");
        txf_nacional.setText("");
        txf_nombre.setText("");

    }//GEN-LAST:event_bt_guardarActionPerformed

    private void txf_documentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txf_documentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txf_documentoActionPerformed

    private void txf_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txf_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txf_nombreActionPerformed

    private void tipo_docActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipo_docActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipo_docActionPerformed

    private void txf_edadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txf_edadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txf_edadActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Decoration1;
    private javax.swing.JLabel Decoration2;
    private javax.swing.JLabel Label_Tdoc;
    private javax.swing.JLabel Label_doc;
    private javax.swing.JLabel Label_edad;
    private javax.swing.JLabel Label_nac;
    private javax.swing.JLabel Label_nacional;
    private javax.swing.JLabel Label_nom;
    private javax.swing.JLabel Subtext_Tdoc;
    private javax.swing.JLabel Subtext_doc;
    private javax.swing.JLabel Subtext_edad;
    private javax.swing.JLabel Subtext_nac;
    private javax.swing.JLabel Subtext_nacionalidad;
    private javax.swing.JLabel Subtext_nom;
    private javax.swing.JLabel Subtitle;
    private javax.swing.JLabel Title;
    private javax.swing.JButton bt_guardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JComboBox<String> tipo_doc;
    private javax.swing.JTextField txf_documento;
    private javax.swing.JTextField txf_edad;
    private javax.swing.JTextField txf_fecha_na;
    private javax.swing.JTextField txf_nacional;
    private javax.swing.JTextField txf_nombre;
    // End of variables declaration//GEN-END:variables
}
