package app.ui;


import app.pages.Pg_info_eco;
import app.pages.Pg_info_per;
import app.pages.Pg_info_res;
import java.awt.BorderLayout;
import javax.swing.JPanel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author sergi
 */
public class DashBoard extends javax.swing.JPanel {

    /**
     * Creates new form Dashboard
     */
    public DashBoard() {
        initComponents();
        Pg_info_res p4 = new Pg_info_res();
        ShowPanel(p4);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bt_info_res = new javax.swing.JButton();
        bt_info_per = new javax.swing.JButton();
        bt_info_eco = new javax.swing.JButton();
        content = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(242, 245, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bt_info_res.setText("Resumen Principal");
        bt_info_res.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_info_resActionPerformed(evt);
            }
        });
        add(bt_info_res, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 288, 233, -1));

        bt_info_per.setText("Infomación Personal");
        bt_info_per.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_info_perActionPerformed(evt);
            }
        });
        add(bt_info_per, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 414, 233, -1));

        bt_info_eco.setText("Infomación Económica");
        bt_info_eco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_info_ecoActionPerformed(evt);
            }
        });
        add(bt_info_eco, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 351, 233, -1));

        content.setBackground(new java.awt.Color(255, 255, 255));
        content.setPreferredSize(new java.awt.Dimension(768, 0));

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 991, Short.MAX_VALUE)
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
        );

        add(content, new org.netbeans.lib.awtextra.AbsoluteConstraints(277, 0, 991, 720));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/img_DSH.png"))); // NOI18N
        jLabel3.setToolTipText("");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 35, 177, 214));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 329, 233, 10));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 392, 233, 10));
    }// </editor-fold>//GEN-END:initComponents

    private void bt_info_resActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_info_resActionPerformed
        Pg_info_res p1 = new Pg_info_res();
        ShowPanel(p1);
   
    }//GEN-LAST:event_bt_info_resActionPerformed

    private void bt_info_perActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_info_perActionPerformed
        Pg_info_per p2 = new Pg_info_per();
        ShowPanel(p2);
    }//GEN-LAST:event_bt_info_perActionPerformed

    private void bt_info_ecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_info_ecoActionPerformed
        Pg_info_eco p3 = new Pg_info_eco();
        ShowPanel(p3);
    }//GEN-LAST:event_bt_info_ecoActionPerformed
    private void ShowPanel(JPanel p) {
        p.setSize(1003, 720);
        p.setLocation(0, 0);
        content.removeAll();
        content.add(p, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_info_eco;
    private javax.swing.JButton bt_info_per;
    private javax.swing.JButton bt_info_res;
    private javax.swing.JPanel content;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
