package app.ui;


import java.awt.BorderLayout;
import javax.swing.JPanel;
import javax.swing.*;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author sergi
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public static JPanel panelInicioStatic;

    public Inicio() {
        initComponents();
        panelInicioStatic = cn_inicio;
        this.setSize(1296, 759);
        this.setLocationRelativeTo(null);// guardar referencia original
    }

    public static JPanel getPanelInicioStatic() {
        return panelInicioStatic;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cn_inicio = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        bt_login = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        bt_regis = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 52, 89));
        setMaximumSize(new java.awt.Dimension(1280, 720));
        setMinimumSize(new java.awt.Dimension(1280, 720));

        cn_inicio.setBackground(new java.awt.Color(255, 255, 255));
        cn_inicio.setMaximumSize(new java.awt.Dimension(1280, 720));
        cn_inicio.setOpaque(false);
        cn_inicio.setPreferredSize(new java.awt.Dimension(656, 441));
        cn_inicio.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(107, 77, 37));
        jLabel3.setFont(new java.awt.Font("Overpass", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(68, 75, 89));
        jLabel3.setText("Bienvenido a PIM");
        cn_inicio.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 160, -1, 73));

        bt_login.setBackground(new java.awt.Color(47, 33, 0));
        bt_login.setFont(new java.awt.Font("Nunito ExtraLight", 1, 36)); // NOI18N
        bt_login.setForeground(new java.awt.Color(255, 255, 255));
        bt_login.setText("Iniciar sesión");
        bt_login.setBorder(null);
        bt_login.setBorderPainted(false);
        bt_login.setContentAreaFilled(false);
        bt_login.setOpaque(false);
        bt_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_loginActionPerformed(evt);
            }
        });
        cn_inicio.add(bt_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(472, 460, 340, 60));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Sign In_in.png"))); // NOI18N
        cn_inicio.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 460, 400, 70));

        bt_regis.setBackground(new java.awt.Color(107, 77, 37));
        bt_regis.setFont(new java.awt.Font("Nunito ExtraLight", 0, 36)); // NOI18N
        bt_regis.setForeground(new java.awt.Color(255, 255, 255));
        bt_regis.setText("Registrarse");
        bt_regis.setBorder(null);
        bt_regis.setContentAreaFilled(false);
        bt_regis.setMaximumSize(new java.awt.Dimension(244, 314));
        bt_regis.setOpaque(false);
        bt_regis.setPreferredSize(new java.awt.Dimension(244, 300));
        bt_regis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_regisActionPerformed(evt);
            }
        });
        cn_inicio.add(bt_regis, new org.netbeans.lib.awtextra.AbsoluteConstraints(472, 550, 340, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Sign In_in.png"))); // NOI18N
        cn_inicio.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 550, 400, 70));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Cover.png"))); // NOI18N
        cn_inicio.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, -1));

        getContentPane().add(cn_inicio, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_regisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_regisActionPerformed
        Registro p1 = new Registro();
        ShowPanel(p1);
    }//GEN-LAST:event_bt_regisActionPerformed

    private void bt_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_loginActionPerformed
        Login p2 = new Login();
        ShowPanel(p2);
    }//GEN-LAST:event_bt_loginActionPerformed
    void ShowPanel(JPanel p) {
        p.setSize(1280, 720);
        p.setLocation(0, 0);
        cn_inicio.removeAll();
        cn_inicio.setLayout(new BorderLayout());
        cn_inicio.add(p, BorderLayout.CENTER);
        cn_inicio.revalidate();
        cn_inicio.repaint();

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_login;
    private javax.swing.JButton bt_regis;
    private javax.swing.JPanel cn_inicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
